### ISSUE TITLE
Failed codecov run

### ISSUE THREAD

**Issue by jkbrooks** [ai16z/eliza#663]
We need to fix https://github.com/ai16z/eliza/actions/runs/12075056047 which appears related to 

https://github.com/ai16z/eliza/pull/608 and might get fixed with https://github.com/ai16z/eliza/pull/659 @snobbee @monilpat @pgoos

**Comment by monilpat** [comment]
@jkbrooks Thanks so much for flagging! From looking at the logs not sure that this is related to codecov or that it will be fixed by #659. Would love to get context on why you think that is because from looking at logs it seems like the install dependencies step is hanging it took 6 hours to run. The same step succeeded in the PR in 26 seconds so will try to run it locally and see what happens with that step.

**Comment by monilpat** [comment]
> @jkbrooks Thanks so much for flagging! From looking at the logs not sure that this is related to codecov or that it will be fixed by #659. Would love to get context on why you think that is because from looking at logs it seems like the install dependencies step is hanging it took 6 hours to run. The same step succeeded in the PR in 26 seconds so will try to run it locally and see what happens with that step. Because it is failing in the install dependencies step and not even getting to the codecov step.

Can you try to rerun it too?

**Comment by monilpat** [comment]
This can be closed :)
